### ISSUE TITLE
Web of trust

### ISSUE THREAD

**Issue by cromerc** [cromnix/cromnix-keyring#1]
I believe the problem with the wot is that we don't have enough signatures setup. I think that after artoo signs the packagers and other master keys with his master key the problem will fix itself.

**Comment by udeved** [comment]
Yes, we have to sign each others keys.

```
gpg --recv-keys id_1 id_2
gpg --sign-key id_1 id_2
gpg --send-keys id_1 id_2
```

**Comment by cromerc** [comment]
Alright, once I get out of class I will send you my keys.

**Comment by cromerc** [comment]
Fixed: https://github.com/cromnix/cromnix-keyring/commit/ce04b92b59b7db902e9a8e1eb73dc1a799edf064
